version: 1
services:
  web:
    type: python
    name: apexora-stock-crypto-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      FLASK_ENV: production
      PORT: 10000